### ISSUE TITLE
uploading of update from web interface fails

### ISSUE THREAD

**Issue by jbrzusto** [jbrzusto/sensorgnome-pi#7]
traceback in node log:

```
TypeError: Cannot read property 'update_archive' of undefined
    at WebServer.uploadSoftwareUpdate (/home/pi/proj/bonedongle/master/webserver.js:69:63)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/usr/local/lib/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/usr/local/lib/node_modules/express/lib/router/index.js:330:12)
    at next (/usr/local/lib/node_modules/express/lib/router/index.js:271:10)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/usr/local/lib/node_modules/express/lib/router/index.js:312:13)
```

**Comment by jbrzusto** [comment]
node package "Express" no longer contains middleware for file upload.

fix is:
```bash
  npm install multer
```
and then some changes to `webserver.js`

Do node packges reside entirely within their folder in /usr/local/lib/node_modules,
so that the appropriate folders there are all we need to supply the results of the
`npm` command above?

**Comment by jbrzusto** [comment]
"Fixed" but not for end-users; needs a new image...

**Comment by jbrzusto** [comment]
fixed in pending image.
